EveripediaNetwork/iq-bridge-ui

- .eslintrc.json
- .prettierrc
- src/App.js
- src/components/errorBoundary.js
- src/components/layouts/LanguageMenu/LanguageList.js
- src/components/layouts/LanguageMenu/LanguageSelector.js
- src/components/layouts/layout.js
- src/components/ui/addressContainer.js
- src/components/ui/cardTitle.js
- src/components/ui/ethereumWalletModal.js
- src/components/ui/infoAlert.js
- src/components/ui/swapContainer.js
- src/components/ui/txSuccessAlert.js
- src/config.js
- src/constants/index.js
- src/context/walletProvider/walletProviderFacade.js
- src/features/eth.js
- src/features/home.js
- src/features/loading.js
- src/hooks/useAsync.js
- src/scss/theme.scss
- src/utils/EosDataProvider.js
- src/utils/EthDataProvider.js
- src/utils/UalProvider.js
- src/utils/analytics.js
- src/utils/i18n.js
When working with multiple developers it is important to establish standards, that way the code syntax is similar and more readable.
_Nothing to test_
closes #2
> feat: code styling

- .eslintrc.json
- craco.config.js
- package.json
- src/App.js
- src/components/errorBoundary.js
- src/components/layouts/LanguageMenu/LanguageSelector.js
- src/components/layouts/layout.js
- src/components/ui/addressContainer.js
- src/components/ui/cardTitle.js
- src/components/ui/ethereumWalletModal.js
- src/components/ui/infoAlert.js
- src/components/ui/swapContainer.js
- src/components/ui/txSuccessAlert.js
- src/context/walletProvider/walletProviderFacade.js
- src/features/error.js
- src/features/eth.js
- src/features/home.js
- src/features/loading.js
- src/hooks/useGoogleAnalytics.js
- src/utils/UalProvider.js
_This PR includes some code refactoring along with small improvements_
1. `yarn start` and that's it
_We've got no observations for this PR_
closes #4
> refactor: code refactoring

- src/components/ui/swapContainer.js
- src/features/Lock/lock.js
- src/features/Lock/lockHeader.js
- src/features/home.js
_Some bug fixes_
_Make sure you setup env vars correctly_
closes #28
> fix: avoid input special chars in the swap input

- src/components/ui/txDetailsDialog.js
- src/utils/EthDataProvider/EthDataProvider.js
- src/utils/EthDataProvider/erc20.abi.js
This PR reduces the needs of approve calls creating an unlimit approval first time, and checking approval during next calls.
This is very useful for users who use more than once the bridge / hiIQ saving around 4-6$ per swap
> allowance issue

- src/utils/SnapshotProvider.js
_Filter the "ee" proposal_
1. yarn start
_no observations_
not necessary to link any issues (small fix)
> fix: filter ee proposal

- src/features/Voting/votingChart.js
- src/features/Voting/votingProposalForm.js
- src/utils/i18n.js
_Add some i18n missing keys and remove unecessary code_
_no observations for this PR_
no linked issues
> fix: i18n fixes and remove unecessary code

- src/features/Voting/voting.js
- src/utils/SnapshotProvider.js
_It was needed to show the right selected choice depending of the selected proposal_
_no observations for this PR_
closes #75
> fix: show pie chart along with bug fixes

- src/utils/i18n.js
_CZ-KO updates_
_we've got no observations here_
closes #74
> cz-ko-updates

- src/App.js
- src/components/layouts/layout.js
- src/components/ui/wrongChainModal.js
- src/context/wrongChainContext.js
- src/features/Lock/lock.js
- src/features/Voting/voting.js
- src/features/eth.js
- src/features/home.js
_The idea with this PR is to provide a global state about the actual chain in the browser session_
_we've got no observations_
closes #43
> refactor: move wrong chain dialog

- src/features/Lock/lock.js
- src/features/eth.js
- src/utils/EthDataProvider/EthDataProvider.js
- src/utils/i18n.js
_Remove invalid and inexistent code_
> fix: remove invalid code

- src/components/ui/voteBreakdown.js
- src/features/Voting/voting.js
- src/features/Voting/votingChart.js
_This PR provides fixes for the voting section, e.g update the chart when a new vote is broadcasted along with other minor fixes_
_no observations for this PR_
closes #88
> fix: bug fixes

- src/features/Lock/lock.js
- src/utils/EthDataProvider/EthDataProvider.js
- src/utils/EthDataProvider/hiIQ.abi.js
- src/utils/i18n.js
- HIIQ abi was updated
- Info about the expiring date
closes #95
> Withdraw expired tokens functionality

- src/utils/EthDataProvider/EthDataProvider.js
_Hardcoded some gas values to avoid operation failure_
> fix: update gas values

- src/utils/EthDataProvider/EthDataProvider.js
_Fix estimate gas error_
_No observations_
closes #102
> fix: closes #102

- src/features/Lock/lock.js
- src/utils/i18n.js
_Show information related to the amount of IQ you'll get after 1, 2, 3 & 4 years of locking_
closes #115
> feat#115: show iq rewards after periods of time

- src/features/Lock/lockStats.js
_PR description escription goes here_
1. Step one
2. Step two
3. ...
_jot down something here_
closes #00, closes #001, etc
> staking disabled

- src/utils/EthDataProvider/EthDataProvider.js
_I went through the commit history and the gas limit is set to its previous value_
closes #118
> fix: iq to eos

- src/components/ui/statsCharts.js
_Use fixed fixed colors instead of random ones_
_no observations for this pr_
closes #138
> fix: use colors array instead of random colors

- src/features/Lock/lock.js
- src/features/Lock/lockPeriod.js
_Fix increase unlock time bug when increasing & decreasing using the slider_
2. Play with the slider and see if everything works well
_no observations for this PR_
closes #134 #148
> fix: increase unlock time situation with weeks when increasinng & decreasing

- src/components/ui/swapContainer.js
- src/features/Lock/lock.js
- src/features/Lock/lockPeriod.js
- src/utils/EthDataProvider/EthDataProvider.js
- src/utils/methods.js
- Correctly call button disabled validation
- Prevent rounding error when set max available lock time
Test report: https://docs.google.com/spreadsheets/d/1GuZNrp8Iwm_72bYQ0sBScVCtt5fMW3UrMZXPZY4TWVY/edit?usp=sharing
closes #153 #155
> fix: lock related fixes

- src/components/ui/statsCharts.js
- src/features/Lock/stats.js
_Remove labels from "Top 10 Stakers" chart to make it a little big bigger. Increase the height for the first chart also._
we've got no observations
closes https://github.com/EveripediaNetwork/issues/issues/32
> fix: remove labels for the chart and make them a little bt bigger

- package.json
- src/features/eth.js
- src/utils/i18n.js
- yarn.lock
_Enable add IQ token to metamask_
> feat: add iq token to metamask
